// 每一节的英文说明，用作 Jev choice 问题的选项描述（Jev 对英文最准确）。
export const CHAPTER_EN: Record<number, string> = {
  1: "Avoiding early death: accidents (car crashes, seatbelts, helmets, fire, gas, carbon monoxide, drowning), key vaccines and screenings, warning symptoms that need a doctor",
  2: "Avoiding slow death from chronic risk: smoking, alcohol, betel nut, diet, salt, sugar drinks, processed food, exercise, sitting, sleep, weight, blood pressure",
  3: "Saving energy and attention: focus, interruptions, sleep quality, fatigue, low mood, productivity at work or study",
  4: "Saving time: procrastination, time management, commuting, phone and short-video use, chores, deadlines",
  5: "Not wasting money: spending, subscriptions, taxes, housing fund, saving, loans and interest, investing, funds, stocks, crypto, lottery, buying insurance (critical illness, life, medical, car)",
  6: "Things that look cheap and effective but are not: supplements, health products, fads, pseudo-science, useless purchases and treatments",
  7: "Surviving with no money: unemployment, being laid off, welfare benefits, subsidies, minimum living allowance, free public services, medical aid, debt hardship",
  8: "Not ruining yourself legally and financially: guaranteeing loans for friends, lending money, IOUs, signing contracts, scams and fraud, marriage property, bride price, inheritance, lawsuits, protecting assets",
  9: "Everyday legal red lines for ordinary people: things that lead to detention, fines or criminal charges (drunk driving, fights, gambling, drugs, renting out bank cards, online speech)",
  10: "Is dating and marriage worth it: relationships, getting married, divorce, prenuptial matters, costs and benefits of marriage",
  11: "Legal red lines for programmers and tech workers: web scraping, hacking, gray-market apps, data and privacy, cracking software, crypto/payment systems",
  12: "Starting a business: opening a shop or company, partnerships, liability, personal guarantees, company debt, contracts, taxes for business owners",
  13: "Emergencies: what to do first in accidents, first aid, CPR, choking, disasters, wilderness danger, threats, extortion, ongoing scams, police",
  14: "Account and information security: passwords, two-factor authentication, phone number, account theft, personal data leaks, identity theft",
  15: "Renting and buying a home: deposits, agents, rental contracts, mortgages, buying property, hidden defects",
  16: "Living with a chronic disease after diagnosis: diabetes, hypertension, long-term disease management, medication, costs",
  17: "Having elderly parents at home: elder care, guardianship, wills, nursing, falls, dementia, bedridden care, cataract",
  18: "Is having children worth it: money and time cost of raising kids, deciding whether to have a child",
  19: "On the job, quitting and work injury: labor contracts, wages, overtime, resignation, layoffs and severance, labor arbitration, occupational disease, workplace injury, workplace bullying",
  20: "Caring for a newborn baby: infant safety, safe sleep, vaccines, feeding, baby costs in the first year",
  21: "Travel abroad and overseas safety: visas, foreign laws, consular help, travel insurance, safety while traveling",
  22: "Relaxing: entertainment venues (KTV, bars, massage), being overcharged, fire exits, stress relief and decompression",
  23: "Which skills are worth learning: whether to keep studying, degrees, vocational skills, certificates, career skills, education value",
  24: "Seeing a doctor: which hospital to go to, referrals, emergency room, saving medical costs, medical insurance reimbursement, disability assessment after injury",
  25: "After someone dies: funeral procedures, death certificate, cremation, inheritance of accounts, bereavement paperwork",
  26: "Building a website or online platform: licenses, ICP filing, servers, user content liability, payments",
  27: "Pregnancy and childbirth: prenatal checks, delivery, maternity leave, birth registration paperwork",
  28: "Not harming your body for appearance: dieting, weight-loss drugs, injections, cosmetic surgery",
  29: "After a major blow: grief after a death, serious diagnosis, job loss, divorce, suicide risk, avoiding big decisions during crisis",
  30: "School-age children (3-18): screen time, education, bullying, mental health, safety, child development",
  31: "Paths after age 18: college entrance exam choices, military service, civil service, vocational school, working, gap options",
  32: "Studying abroad: student visa status, part-time work limits, insurance, degree recognition after returning",
  33: "Living with a disability: disability certificate, benefits, rehabilitation, employment, accessibility",
  34: "Household over-the-counter medicines: fever reducers, painkillers, cold medicine, overdose and interaction dangers",
};
